# 3 second seeks
LEFT seek -3 exact
RIGHT seek 3 exact
WHEEL_UP seek 3 exact
WHEEL_DOWN seek -3 exact
WHEEL_LEFT seek -3 exact
WHEEL_RIGHT seek 3 exact

# Keep mpv's useful fine seek defaults.
Shift+LEFT seek -1 exact
Shift+RIGHT seek 1 exact
